### ISSUE TITLE
Rule: check if initialization files does not contain restricted element

### ISSUE THREAD

**Issue by mnojek** [bhirsz/robotframework-robocop#108]
Typically _\_\_init\_\_.robot_ file cannot contain Test Cases section and some settings are not supported

**Comment by bhirsz** [comment]
It's already covered by ParsingErrorChecker. Before scanning files we run recognize_file_types() which detects if the file is Resource type (it's only if it's imported by other file). File type is used to select Robot parser type -> if we select resource parser for file that contains test cases, it will throw Robot parsing error and it will be caught by ParsingErrorChecker
