### ISSUE TITLE
Does invalid name checker should also check suite name?

### ISSUE THREAD

**Issue by mnojek** [bhirsz/robotframework-robocop#109]
Robot is using `.` as path separator so using it in suite name can lead to ambiguity.
https://github.com/bhirsz/robotframework-robocop/blob/bd94107dc0394def100885919dcd5832b84a27d8/robocop/checkers/naming.py#L13
What do you think, @bhirsz ?

**Comment by bhirsz** [comment]
Yes, we definitely need to add check for suite name too.

**Comment by bhirsz** [comment]
What is not possible is to check directory names unless someone created __init__.robot file (then I check parent dir). But all filename will be checked for invalid chars
