### ISSUE TITLE
Improve methods of disabling rule from comment (# robocop=disable:rulename,rulename2)

### ISSUE THREAD

**Issue by bhirsz** [bhirsz/robotframework-robocop#22]

**Comment by mnojek** [comment]
I would also allow to disable all rules for a specific line with a comment `# robocop=disable` and exclude it for all rules and checkers

**Comment by bhirsz** [comment]
There is typo in title, what I meant is : 
#  robocop:disable=rulename, rulename
Or to match all
# robocop:disable

It will work only for current line.

**Comment by bhirsz** [comment]
Together with this feature I also added feature for disabling checkers for whole blocks or files. 

# robocop: disable:rule1,rule2
some lines of code..
# robocop: enable:rule2
some lines of code..

Will disable rule2 checks until enable command. rule1 will stay disabled until end of file 

If # robocop: disable is provided in first line, whole file will be ignored (not parsed at all).
