### ISSUE TITLE
Rule: too-many-arguments

### ISSUE THREAD

**Issue by bhirsz** [bhirsz/robotframework-robocop#83]
Too many arguments used in keyword call or definition. For example:

```
My Keyword  ${var1}  1  smth  ${var2}  10 ...
```

**Comment by mnojek** [comment]
What about adding a suggestion that when too many arguments are called or created for a keyword, it is better to keep them on a separate lines?
And please add description to this issue, because I can think of several things it can relate to 😄

**Comment by bhirsz** [comment]
> What about adding a suggestion that when too many arguments are called or created for a keyword, it is better to keep them on a separate lines?
> And please add description to this issue, because I can think of several things it can relate to 😄

Yeah we can do such suggestion, probably with Info severity. With first argument in the same line as keyword call?

**Comment by mnojek** [comment]
> > What about adding a suggestion that when too many arguments are called or created for a keyword, it is better to keep them on a separate lines?
> > And please add description to this issue, because I can think of several things it can relate to 😄
> 
> Yeah we can do such suggestion, probably with Info severity. With first argument in the same line as keyword call?

I think it's better to keep even first on separate line but that is only my approach I use.

**Comment by bhirsz** [comment]
It's almost dangerous area of long and unfinished C++/Java/C# wars :D 

```
if () {

}
```

vs

```
if ()
{

}
```

We can always make it configurable - > -c many-arguments-in-one-line:first_argument_in_next_line:False etc.

**Comment by mnojek** [comment]
I think we are trying to impose too much on the testers 😉 Maybe let's stick with just an info that it's good to split arguments into separate lines for readability?
